language: java

addons:
  chrome: stable

install: ./gradlew clean testClasses

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script: ./gradlew clean test allureReport -Preport=allure

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build/reports/allure-report
  repo: andrcuns/andrcuns.github.io
  target_branch: master
  on:
    branch: master