sudo: required

language: java
jdk:
  - oraclejdk9

addons:
  chrome: stable

install: ./gradlew clean testClasses

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then ./gradlew clean checkQualityTest checkQualityMain; fi
  - ./gradlew clean runCukeTestsInParallel -Dselenide.headless=true

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build/reports/allure-report
  repo: andrcuns/andrcuns.github.io
  target_branch: master

branches:
  only:
    - master